// auth
export const REQUESTING_AUTH_DATA = 'REQUESTING_AUTH_DATA';
export const RECEIVED_AUTH_DATA = 'RECEIVED_AUTH_DATA';
export const CHECK_FOR_ADMIN = 'CHECK_FOR_ADMIN';
export const GET_USER = 'GET_USER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const USER_IS_ADMIN = 'USER_IS_ADMIN';

// main window
export const SHOW_DASHBOARD = 'SHOW_DASHBOARD';
export const SHOW_CONTENT_TYPES = 'SHOW_CONTENT_TYPES';
export const SHOW_USERS = 'SHOW_USERS';
export const SHOW_CONTENT = 'SHOW_CONTENT';

// users
export const REQUESTING_USERS_DATA = 'REQUESTING_USERS_DATA';
export const RECEIVED_USERS_DATA = 'RECEIVED_USERS_DATA';
export const GET_USERS = 'GET_USERS';

// content types
export const REQUESTING_CONTENT_TYPES_DATA = 'REQUESTING_CONTENT_TYPES_DATA';
export const RECEIVED_CONTENT_TYPES_DATA = 'RECEIVED_CONTENT_TYPES_DATA';
export const GET_CONTENT_TYPES = 'GET_CONTENT_TYPES';

// content
export const REQUESTING_CONTENT_DATA = 'REQUESTING_CONTENT_DATA';
export const RECEIVED_CONTENT_DATA = 'RECEIVED_CONTENT_DATA';
export const SET_CURRENT_CONTENT_TYPE = 'SET_CURRENT_CONTENT_TYPE';
export const GET_ALL_CONTENT = 'GET_ALL_CONTENT';
export const SET_FIRST_FIELD = 'SET_FIRST_FIELD';