export const AUTH_ADMIN_EXISTS_REQUEST = 'auth/AUTH_ADMIN_EXISTS_REQUEST';
export const AUTH_ADMIN_EXISTS_SUCCESS = 'auth/AUTH_ADMIN_EXISTS_SUCCESS';
export const AUTH_ADMIN_EXISTS_ERROR = 'auth/AUTH_ADMIN_EXISTS_ERROR';

export const AUTH_USER_REQUEST = 'auth/AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'auth/AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'auth/AUTH_USER_ERROR';